### ISSUE TITLE
Secret Creation for ROSA - Non STS Cluster

### ISSUE THREAD

**Issue by nfrankish** [openshift/aws-load-balancer-operator#121]
The documentation provided has options for ROSA around creating the credential when its a STS enabled cluster - see https://access.redhat.com/documentation/en-us/red_hat_openshift_service_on_aws/4/html/tutorials/cloud-experts-aws-load-balancer-operator.

However on a non STS ROSA cluster, there is no documentation for the requirements or provisioning of the secret.

The operator fails to install, and the operator details page highlights that a secret needs to be created (see attachment 1) - however, in a ROSA cluster that action is blocked - See attachment 2

![secretcreate1](https://github.com/openshift/aws-load-balancer-operator/assets/762614/28d821dc-6e53-4d60-bccc-cdd459a0e7ad)

![secretcreate2](https://github.com/openshift/aws-load-balancer-operator/assets/762614/589b267d-9089-450d-8b54-18badc8879ab)

**Comment by alebedev87** [comment]
I'm not a ROSA expert and I cannot say to which extent the non STS mode is recommended. I just know that it's not the default mode anymore. So, I don't know whether it's a documentation gap or an intent.

As a workaround I can propose to use [the OCP documentation](https://docs.openshift.com/container-platform/4.13/networking/aws_load_balancer_operator/installing-albo-sts-cluster.html#nw-bootstra-albo-on-sts-cluster_albo-sts-cluster).

**Comment by nfrankish** [comment]
Yeah appreciate that its now no longer the default, however we have two existing clusters that were stuck with for the forseable future. That documentation appears to still be fore a STS cluster. Ill open a case with RedHat as well for options.

**Comment by alebedev87** [comment]
@nfrankish : I believe the creation of `CredentialsRequest` resources was unblocked in the recent ROSA versions. That allowed us to implement a new STS flow based on the self credentials provisioning, see https://github.com/openshift/aws-load-balancer-operator/pull/113. [The OCP documentation](https://docs.openshift.com/container-platform/4.14/networking/aws_load_balancer_operator/installing-albo-sts-cluster.html) can help you to understand how to create and provide IAM role for the operator and controller (ROSA uses STS mode by default).

**Comment by nfrankish** [comment]
Thanks for the update - i know it started working for us recently, so probably related. Thanks for checking in!
