### ISSUE TITLE
Roadmap Item? 

### ISSUE THREAD

**Issue by bloxsome** [openshift/aws-load-balancer-operator#124]
https://aws.amazon.com/blogs/aws/mutual-authentication-for-application-load-balancer-to-reliably-verify-certificate-based-client-identities/

**Comment by alebedev87** [comment]
The upstream [seems to start working](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/3499#issuecomment-1837792951) on the mTLS support. So, yes, that should come in the future.

**Comment by alebedev87** [comment]
Closing this one in favor of https://issues.redhat.com/browse/RFE-5165.
