### ISSUE TITLE
The operator failed to start

### ISSUE THREAD

**Issue by datianshi** [openshift/aws-load-balancer-operator#77]
Seems the operator does not have a projected token configured.
I wonder how does this work with STS

{"error": "failed to list VPC with tag \"kubernetes.io/cluster/${cluster_name}\": operation error EC2: DescribeVpcs, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, failed to retrieve jwt from provide source, unable to read file at /var/run/secrets/openshift/serviceaccount/token: open /var/run/secrets/openshift/serviceaccount/token: no such file or directory"}

**Comment by thejasn** [comment]
Hey @datianshi,
The operator is supported on STS clusters as well. Both on non-STS cluster and STS cluster have a prerequisite during installation. You can find the documentation for the same [here](https://github.com/openshift/aws-load-balancer-operator/blob/main/docs/prerequisites.md).

**Comment by datianshi** [comment]
@thejasn Understand the STS. I think the issue still exists as there is no projected token configured in the manager. 
I created a PR here -> https://github.com/openshift/aws-load-balancer-operator/pull/78

**Comment by alebedev87** [comment]
Addressed in https://github.com/openshift/aws-load-balancer-operator/pull/82
